# Generated by Django 5.2 on 2025-05-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
