# Generated by Django 5.2 on 2025-05-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='locked',
        ),
    ]
