# Generated by Django 5.2 on 2025-05-06 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shopping_list', '0005_remove_cartitem_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='ShoppingList',
        ),
        migrations.RenameModel(
            old_name='CartItem',
            new_name='ShoppingListItem',
        ),
    ]
