# Generated by Django 5.2 on 2025-05-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('is_proxy', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Monitoring',
        ),
    ]
