# Generated by Django 5.2 on 2025-04-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('verification_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempt_number', models.IntegerField(default=0)),
                ('is_latest', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationType',
            fields=[
                ('verification_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('requires_token', models.BooleanField(default=True)),
                ('expires_on', models.DurationField()),
            ],
        ),
    ]
