# Generated by Django 5.2 on 2025-04-19 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userverification_verificationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='user',
            field=models.ForeignKey(default='f7af5ad8-18ee-4ddc-b44b-1451abd54c0f', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
