# Generated by Django 5.2 on 2025-04-19 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userverification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='verification_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.verificationtype'),
            preserve_default=False,
        ),
    ]
