# Generated by Django 5.2 on 2025-04-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userverification_verification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_entered', models.CharField(max_length=50)),
                ('success', models.BooleanField()),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device', models.TextField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
