# Generated by Django 5.2 on 2025-04-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_mfa_enabled_customuser_mfa_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_attempt', 'Login Attempt'), ('password_reset', 'Password Reset'), ('email_verified', 'Email Verified'), ('logout', 'Logout'), ('profile_updated', 'Profile Updated'), ('mfa_setup_started', 'MFA Setup Started'), ('mfa_verified', 'MFA Verified'), ('mfa_login', 'MFA Login')], max_length=100),
        ),
    ]
