# Generated by Django 5.2 on 2025-04-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_cookieconsent_cookies'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cookies',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='cookie_selection',
            field=models.CharField(choices=[('mandatory_only', 'Mandatory Only'), ('mandatory_and_analytics', 'Mandatory and Analytics')], default='mandatory_only', max_length=30),
        ),
    ]
