# Generated by Django 5.2 on 2025-04-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_cookies_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('login_attempt_count', models.IntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='cooldown_strikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_attempt', 'Login Attempt'), ('password_reset', 'Password Reset'), ('email_verified', 'Email Verified'), ('logout', 'Logout'), ('profile_updated', 'Profile Updated'), ('mfa_setup_started', 'MFA Setup Started'), ('mfa_verified', 'MFA Verified'), ('mfa_login', 'MFA Login'), ('user_temp_blocked', 'User Temporarily Blocked'), ('user_permanently_blocked', 'User Permanently Blocked'), ('ip_blocked', 'IP Blocked'), ('rate_limit_triggered', 'Rate Limit Triggered')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='loginattempts',
            index=models.Index(fields=['user'], name='users_login_user_id_b32caf_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempts',
            index=models.Index(fields=['email_entered'], name='users_login_email_e_7d5925_idx'),
        ),
    ]
