# Generated by Django 5.2 on 2025-05-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_ipaddressban_customuser_cooldown_strikes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_entered', models.CharField(max_length=50)),
                ('success', models.BooleanField()),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device', models.TextField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email_entered'], name='users_signu_email_e_9cf822_idx'), models.Index(fields=['ip_address'], name='users_signu_ip_addr_c9ddc1_idx')],
            },
        ),
    ]
