# Generated by Django 5.2 on 2025-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_signupattempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddressban',
            name='signup_attempt_count',
            field=models.IntegerField(default=0),
        ),
    ]
