# Generated by Django 5.2 on 2025-05-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_pending_email'),
        ('users', '0016_ipaddressban_signup_attempt_count'),
    ]

    operations = [
    ]
