# Generated by Django 5.2 on 2025-05-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20250503_2025'),
        ('users', '0018_alter_auditlog_action_and_more'),
    ]

    operations = [
    ]
