# Generated by Django 5.2 on 2025-04-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_remove_price_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='genericproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='genericproduct',
            name='unit',
            field=models.CharField(choices=[('L', 'Liters'), ('ml', 'Milliliters'), ('g', 'Grams'), ('kg', 'Kilograms'), ('pcs', 'Pieces'), ('ks', "Ks (Czech for 'pieces')")], max_length=10),
        ),
    ]
